In [52]:
import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np

In [55]:
tigers_schedule = schedule_and_record(2025, 'DET')

tigers_schedule.head()

http://www.baseball-reference.com/teams/DET/2025-schedule-scores.shtml

,Date,Tm,Home_Away,Opp,W/L,R,RA,Inn,W-L,Rank,GB,Win,Loss,Save,Time,D/N,Attendance,cLI,Streak,Orig. Scheduled
1,"Thursday, Mar 27",DET,@,LAD,L,4.0,5.0,9.0,0-1,3.0,1.0,Snell,Skubal,Treinen,2:32,D,53595.0,.89,-1,None
2,"Friday, Mar 28",DET,@,LAD,L-wo,5.0,8.0,10.0,0-2,5.0,1.5,García,Brieske,None,2:52,N,52029.0,.85,-2,None
3,"Saturday, Mar 29",DET,@,LAD,L,3.0,7.0,9.0,0-3,5.0,1.5,Banda,Olson,None,2:32,N,51788.0,.88,-3,None
4,"Monday, Mar 31",DET,@,SEA,W,9.0,6.0,9.0,1-3,4.0,1.0,Holton,Hancock,Hurter,2:58,N,15306.0,.85,1,None
5,"Tuesday, Apr 1",DET,@,SEA,W,4.0,1.0,9.0,2-3,1.0,Tied,Mize,Gilbert,Kahnle,2:24,N,17333.0,.89,2,None

In [54]:
tigers_schedule.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 162 entries, 1 to 162
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Date             162 non-null    datetime64[ns]
 1   Tm               162 non-null    object
 2   Home_Away        162 non-null    object
 3   Opp              162 non-null    object
 4   W/L              162 non-null    object
 5   R                162 non-null    float64
 6   RA               162 non-null    float64
 7   Inn              162 non-null    float64
 8   W-L              162 non-null    object
 9   Rank             162 non-null    float64
 10  GB               162 non-null    object
 11  Win              162 non-null    object
 12  Loss             162 non-null    object
 13  Save             162 non-null    object
 14  Time             162 non-null    object
 15  D/N              162 non-null    object
 16  Attendance       161 non-null    float64
 17  cLI              162 non-null    object
 18  Streak           162 non-null    int64
 19  Orig. Scheduled  0 non-null      object
dtypes: datetime64[ns](1), float64(5), int64(1), object(13)
memory usage: 25.4+ KB

In [7]:
tigers_schedule['Date'].head()

1    Thursday, Mar 27
2      Friday, Mar 28
3    Saturday, Mar 29
4      Monday, Mar 31
5      Tuesday, Apr 1
Name: Date, dtype: object

In [8]:
tigers_schedule['Date'] = tigers_schedule['Date'].str.split(',').str[1].str.strip()

In [9]:
tigers_schedule['Date'].head()

1    Mar 27
2    Mar 28
3    Mar 29
4    Mar 31
5     Apr 1
Name: Date, dtype: object

In [10]:
tigers_schedule['Date'] = tigers_schedule['Date'] + ' 2025'

In [11]:
tigers_schedule['Date'].head()

1    Mar 27 2025
2    Mar 28 2025
3    Mar 29 2025
4    Mar 31 2025
5     Apr 1 2025
Name: Date, dtype: object

In [17]:
tigers_schedule['Date'] = tigers_schedule['Date'].str.replace(r"\(\d\)", "", regex=True)
tigers_schedule['Date'] = pd.to_datetime(tigers_schedule['Date'], format='%b %d %Y')

In [18]:
tigers_schedule.dtypes

Date               datetime64[ns]
Tm                         object
Home_Away                  object
Opp                        object
W/L                        object
R                         float64
RA                        float64
Inn                       float64
W-L                        object
Rank                      float64
GB                         object
Win                        object
Loss                       object
Save                       object
Time                       object
D/N                        object
Attendance                float64
cLI                        object
Streak                      int64
Orig. Scheduled            object
dtype: object

In [19]:
tigers_schedule.head()

,Date,Tm,Home_Away,Opp,W/L,R,RA,Inn,W-L,Rank,GB,Win,Loss,Save,Time,D/N,Attendance,cLI,Streak,Orig. Scheduled
1,2025-03-27,DET,@,LAD,L,4.0,5.0,9.0,0-1,3.0,1.0,Snell,Skubal,Treinen,2:32,D,53595.0,.89,-1,None
2,2025-03-28,DET,@,LAD,L-wo,5.0,8.0,10.0,0-2,5.0,1.5,García,Brieske,None,2:52,N,52029.0,.85,-2,None
3,2025-03-29,DET,@,LAD,L,3.0,7.0,9.0,0-3,5.0,1.5,Banda,Olson,None,2:32,N,51788.0,.88,-3,None
4,2025-03-31,DET,@,SEA,W,9.0,6.0,9.0,1-3,4.0,1.0,Holton,Hancock,Hurter,2:58,N,15306.0,.85,1,None
5,2025-04-01,DET,@,SEA,W,4.0,1.0,9.0,2-3,1.0,Tied,Mize,Gilbert,Kahnle,2:24,N,17333.0,.89,2,None

In [20]:
from pybaseball import pitching_stats

In [21]:
pitching_2025 = pitching_stats(2025)

In [22]:
pitching_2025.head()

,IDfg,Season,Name,Team,Age,W,L,WAR,ERA,G,...,Pit+ FC,Stf+ FS,Loc+ FS,Pit+ FS,Stuff+,Location+,Pitching+,Stf+ FO,Loc+ FO,Pit+ FO
1,22267,2025,Tarik Skubal,DET,28,13,6,6.6,2.21,31,...,NaN,113.0,142.0,157.0,116,105,119,NaN,NaN,NaN
0,33677,2025,Paul Skenes,PIT,23,10,10,6.5,1.97,32,...,NaN,90.0,125.0,123.0,107,111,116,NaN,NaN,NaN
4,20778,2025,Cristopher Sanchez,PHI,28,13,5,6.4,2.50,32,...,NaN,NaN,NaN,NaN,114,101,117,NaN,NaN,NaN
5,27463,2025,Garrett Crochet,BOS,26,18,5,5.8,2.59,32,...,123.0,NaN,NaN,NaN,116,99,112,NaN,NaN,NaN
15,17995,2025,Logan Webb,SFG,28,15,11,5.5,3.22,34,...,94.0,NaN,NaN,NaN,105,107,111,NaN,NaN,NaN

In [23]:
pitching_2025.shape

(52, 393)

In [25]:
pitching_2025.columns.tolist()

['IDfg',
 'Season',
 'Name',
 'Team',
 'Age',
 'W',
 'L',
 'WAR',
 'ERA',
 'G',
 'GS',
 'CG',
 'ShO',
 'SV',
 'BS',
 'IP',
 'TBF',
 'H',
 'R',
 'ER',
 'HR',
 'BB',
 'IBB',
 'HBP',
 'WP',
 'BK',
 'SO',
 'GB',
 'FB',
 'LD',
 'IFFB',
 'Balls',
 'Strikes',
 'Pitches',
 'RS',
 'IFH',
 'BU',
 'BUH',
 'K/9',
 'BB/9',
 'K/BB',
 'H/9',
 'HR/9',
 'AVG',
 'WHIP',
 'BABIP',
 'LOB%',
 'FIP',
 'GB/FB',
 'LD%',
 'GB%',
 'FB%',
 'IFFB%',
 'HR/FB',
 'IFH%',
 'BUH%',
 'Starting',
 'Start-IP',
 'Relieving',
 'Relief-IP',
 'RAR',
 'Dollars',
 'tERA',
 'xFIP',
 'WPA',
 '-WPA',
 '+WPA',
 'RE24',
 'REW',
 'pLI',
 'inLI',
 'gmLI',
 'exLI',
 'Pulls',
 'WPA/LI',
 'Clutch',
 'FB% 2',
 'FBv',
 'SL%',
 'SLv',
 'CT%',
 'CTv',
 'CB%',
 'CBv',
 'CH%',
 'CHv',
 'SF%',
 'SFv',
 'KN%',
 'KNv',
 'XX%',
 'PO%',
 'wFB',
 'wSL',
 'wCT',
 'wCB',
 'wCH',
 'wSF',
 'wKN',
 'wFB/C',
 'wSL/C',
 'wCT/C',
 'wCB/C',
 'wCH/C',
 'wSF/C',
 'wKN/C',
 'O-Swing%',
 'Z-Swing%',
 'Swing%',
 'O-Contact%',
 'Z-Contact%',
 'Contact%',
 'Zone%',
 'F-Strike%',
 'SwStr%',
 'HLD',
 'SD',
 'MD',
 'ERA-',
 'FIP-',
 'xFIP-',
 'K%',
 'BB%',
 'SIERA',
 'RS/9',
 'E-F',
 'FA% (sc)',
 'FT% (sc)',
 'FC% (sc)',
 'FS% (sc)',
 'FO% (sc)',
 'SI% (sc)',
 'SL% (sc)',
 'CU% (sc)',
 'KC% (sc)',
 'EP% (sc)',
 'CH% (sc)',
 'SC% (sc)',
 'KN% (sc)',
 'UN% (sc)',
 'vFA (sc)',
 'vFT (sc)',
 'vFC (sc)',
 'vFS (sc)',
 'vFO (sc)',
 'vSI (sc)',
 'vSL (sc)',
 'vCU (sc)',
 'vKC (sc)',
 'vEP (sc)',
 'vCH (sc)',
 'vSC (sc)',
 'vKN (sc)',
 'FA-X (sc)',
 'FT-X (sc)',
 'FC-X (sc)',
 'FS-X (sc)',
 'FO-X (sc)',
 'SI-X (sc)',
 'SL-X (sc)',
 'CU-X (sc)',
 'KC-X (sc)',
 'EP-X (sc)',
 'CH-X (sc)',
 'SC-X (sc)',
 'KN-X (sc)',
 'FA-Z (sc)',
 'FT-Z (sc)',
 'FC-Z (sc)',
 'FS-Z (sc)',
 'FO-Z (sc)',
 'SI-Z (sc)',
 'SL-Z (sc)',
 'CU-Z (sc)',
 'KC-Z (sc)',
 'EP-Z (sc)',
 'CH-Z (sc)',
 'SC-Z (sc)',
 'KN-Z (sc)',
 'wFA (sc)',
 'wFT (sc)',
 'wFC (sc)',
 'wFS (sc)',
 'wFO (sc)',
 'wSI (sc)',
 'wSL (sc)',
 'wCU (sc)',
 'wKC (sc)',
 'wEP (sc)',
 'wCH (sc)',
 'wSC (sc)',
 'wKN (sc)',
 'wFA/C (sc)',
 'wFT/C (sc)',
 'wFC/C (sc)',
 'wFS/C (sc)',
 'wFO/C (sc)',
 'wSI/C (sc)',
 'wSL/C (sc)',
 'wCU/C (sc)',
 'wKC/C (sc)',
 'wEP/C (sc)',
 'wCH/C (sc)',
 'wSC/C (sc)',
 'wKN/C (sc)',
 'O-Swing% (sc)',
 'Z-Swing% (sc)',
 'Swing% (sc)',
 'O-Contact% (sc)',
 'Z-Contact% (sc)',
 'Contact% (sc)',
 'Zone% (sc)',
 'Pace',
 'RA9-WAR',
 'BIP-Wins',
 'LOB-Wins',
 'FDP-Wins',
 'Age Rng',
 'K-BB%',
 'Pull%',
 'Cent%',
 'Oppo%',
 'Soft%',
 'Med%',
 'Hard%',
 'kwERA',
 'TTO%',
 'CH% (pi)',
 'CS% (pi)',
 'CU% (pi)',
 'FA% (pi)',
 'FC% (pi)',
 'FS% (pi)',
 'KN% (pi)',
 'SB% (pi)',
 'SI% (pi)',
 'SL% (pi)',
 'XX% (pi)',
 'vCH (pi)',
 'vCS (pi)',
 'vCU (pi)',
 'vFA (pi)',
 'vFC (pi)',
 'vFS (pi)',
 'vKN (pi)',
 'vSB (pi)',
 'vSI (pi)',
 'vSL (pi)',
 'vXX (pi)',
 'CH-X (pi)',
 'CS-X (pi)',
 'CU-X (pi)',
 'FA-X (pi)',
 'FC-X (pi)',
 'FS-X (pi)',
 'KN-X (pi)',
 'SB-X (pi)',
 'SI-X (pi)',
 'SL-X (pi)',
 'XX-X (pi)',
 'CH-Z (pi)',
 'CS-Z (pi)',
 'CU-Z (pi)',
 'FA-Z (pi)',
 'FC-Z (pi)',
 'FS-Z (pi)',
 'KN-Z (pi)',
 'SB-Z (pi)',
 'SI-Z (pi)',
 'SL-Z (pi)',
 'XX-Z (pi)',
 'wCH (pi)',
 'wCS (pi)',
 'wCU (pi)',
 'wFA (pi)',
 'wFC (pi)',
 'wFS (pi)',
 'wKN (pi)',
 'wSB (pi)',
 'wSI (pi)',
 'wSL (pi)',
 'wXX (pi)',
 'wCH/C (pi)',
 'wCS/C (pi)',
 'wCU/C (pi)',
 'wFA/C (pi)',
 'wFC/C (pi)',
 'wFS/C (pi)',
 'wKN/C (pi)',
 'wSB/C (pi)',
 'wSI/C (pi)',
 'wSL/C (pi)',
 'wXX/C (pi)',
 'O-Swing% (pi)',
 'Z-Swing% (pi)',
 'Swing% (pi)',
 'O-Contact% (pi)',
 'Z-Contact% (pi)',
 'Contact% (pi)',
 'Zone% (pi)',
 'Pace (pi)',
 'FRM',
 'K/9+',
 'BB/9+',
 'K/BB+',
 'H/9+',
 'HR/9+',
 'AVG+',
 'WHIP+',
 'BABIP+',
 'LOB%+',
 'K%+',
 'BB%+',
 'LD%+',
 'GB%+',
 'FB%+',
 'HR/FB%+',
 'Pull%+',
 'Cent%+',
 'Oppo%+',
 'Soft%+',
 'Med%+',
 'Hard%+',
 'EV',
 'LA',
 'Barrels',
 'Barrel%',
 'maxEV',
 'HardHit',
 'HardHit%',
 'Events',
 'CStr%',
 'CSW%',
 'xERA',
 'botERA',
 'botOvr CH',
 'botStf CH',
 'botCmd CH',
 'botOvr CU',
 'botStf CU',
 'botCmd CU',
 'botOvr FA',
 'botStf FA',
 'botCmd FA',
 'botOvr SI',
 'botStf SI',
 'botCmd SI',
 'botOvr SL',
 'botStf SL',
 'botCmd SL',
 'botOvr KC',
 'botStf KC',
 'botCmd KC',
 'botOvr FC',
 'botStf FC',
 'botCmd FC',
 'botOvr FS',
 'botStf FS',
 'botCmd FS',
 'botOvr',
 'botStf',
 'botCmd',
 'botxRV100',
 'Stf+ CH',
 'Loc+ CH',
 'Pit+ CH',
 'Stf+ CU',
 'Loc+ CU',
 'Pit+ CU',
 'Stf+ FA',
 'Loc+ FA',
 'Pit+ FA',
 'Stf+ SI',
 'Loc+ SI',
 'Pit+ SI',
 'Stf+ SL',
 'Loc+ SL',
 'Pit+ SL',
 'Stf+ KC',
 'Loc+ KC',
 'Pit+ KC',
 'Stf+ FC',
 'Loc+ FC',
 'Pit+ FC',
 'Stf+ FS',
 'Loc+ FS',
 'Pit+ FS',
 'Stuff+',
 'Location+',
 'Pitching+',
 'Stf+ FO',
 'Loc+ FO',
 'Pit+ FO']

In [27]:
from pybaseball import statcast
import pandas as pd

statcast_data = statcast(start_dt="2025-03-01", end_dt="2025-10-01")
statcast_data.shape

This is a large query, it may take a moment to complete

C:\Users\Alex\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pybaseball\statcast.py:50: UserWarning:
That's a nice request you got there. It'd be a shame if something were to happen to it.
We strongly recommend that you enable caching before running this. It's as simple as `pybaseball.cache.enable()`.
Since the Statcast requests can take a *really* long time to run, if something were to happen, like: a disconnect;
gremlins; computer repair by associates of Rudy Giuliani; electromagnetic interference from metal trash cans; etc.;
you could lose a lot of progress. Enabling caching will allow you to immediately recover all the successful
subqueries if that happens.
  warnings.warn(_OVERSIZE_WARNING)

Skipping offseason dates

  0%|▍                                                                                 | 1/201 [00:00<01:03,  3.14it/s]C:\Users\Alex\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pybaseball\datahelpers\postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
  1%|▊                                                                                 | 2/201 [00:13<26:48,  8.08s/it]C:\Users\Alex\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pybaseball\datahelpers\postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
  1%|█▏                                                                                | 3/201 [00:14<14:58,  4.54s/it]C:\Users\Alex\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pybaseball\datahelpers\postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
  2%|█▋                                                                                | 4/201 [00:14<10:00,  3.05s/it]C:\Users\Alex\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pybaseball\datahelpers\postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
  2%|██                                                                                | 5/201 [00:18<10:12,  3.13s/it]C:\Users\Alex\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pybaseball\datahelpers\postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
  3%|██▍                                                                               | 6/201 [00:18<07:34,  2.33s/it]C:\Users\Alex\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pybaseball\datahelpers\postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
  3%|██▊                                                                               | 7/201 [00:23<09:30,  2.94s/it]C:\Users\Alex\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pybaseball\datahelpers\postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
  4%|███▎                                                                              | 8/201 [00:25<08:40,  2.70s/it]C:\Users\Alex\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pybaseball\datahelpers\postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
  4%|███▋                                                                              | 9/201 [00:26<06:54,  2.16s/it]C:\Users\Alex\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pybaseball\datahelpers\postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
  5%|████                                                                             | 10/201 [00:27<05:33,  1.74s/it]C:\Users\Alex\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pybaseball\datahelpers\postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
  5%|████▍                                                                            | 11/201 [00:28<04:57,  1.56s/it]C:\Users\Alex\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pybaseball\datahelpers\postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
  6%|████▊                                                                            | 12/201 [00:30<05:28,  1.74s/it]C:\Users\Alex\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pybaseball\datahelpers\postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
  6%|█████▏                                                                           | 13/201 [00:35<08:12,  2.62s/it]C:\Users\Alex\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pybaseball\datahelpers\postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
  7%|█████▋                                                                           | 14/201 [00:35<06:28,  2.08s/it]C:\Users\Alex\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pybaseball\datahelpers\postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
C:\Users\Alex\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pybaseball\datahelpers\postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
  7%|██████                                                                           | 15/201 [00:37<06:07,  1.98s/it]C:\Users\Alex\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pybaseball\datahelpers\postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
  8%|██████▊                                                                          | 17/201 [00:37<03:28,  1.13s/it]C:\Users\Alex\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pybaseball\datahelpers\postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
  9%|███████▎                                                                         | 18/201 [00:38<03:17,  1.08s/it]C:\Users\Alex\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pybaseball\datahelpers\postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
C:\Users\Alex\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pybaseball\datahelpers\postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
  9%|███████▋                                                                         | 19/201 [00:40<03:35,  1.18s/it]C:\Users\Alex\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pybaseball\datahelpers\postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 10%|████████▍                                                                        | 21/201 [00:44<05:01,  1.67s/it]C:\Users\Alex\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pybaseball\datahelpers\postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 11%|████████▊                                                                        | 22/201 [00:54<10:20,  3.47s/it]C:\Users\Alex\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pybaseball\datahelpers\postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 11%|█████████▎                                                                       | 23/201 [00:55<08:16,  2.79s/it]C:\Users\Alex\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pybaseball\datahelpers\postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 12%|█████████▋                                                                       | 24/201 [01:02<11:40,  3.96s/it]C:\Users\Alex\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pybaseball\datahelpers\postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 12%|██████████                                                                       | 25/201 [01:03<09:08,  3.11s/it]C:\Users\Alex\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pybaseball\datahelpers\postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 13%|██████████▍                                                                      | 26/201 [01:03<07:00,  2.40s/it]C:\Users\Alex\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pybaseball\datahelpers\postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 13%|██████████▉                                                                      | 27/201 [01:04<05:43,  1.98s/it]C:\Users\Alex\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pybaseball\datahelpers\postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 14%|███████████▎                                                                     | 28/201 [01:05<04:39,  1.61s/it]C:\Users\Alex\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pybaseball\datahelpers\postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 14%|███████████▋                                                                     | 29/201 [01:06<04:30,  1.57s/it]C:\Users\Alex\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pybaseball\datahelpers\postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 15%|████████████                                                                     | 30/201 [01:07<03:41,  1.29s/it]C:\Users\Alex\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pybaseball\datahelpers\postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 15%|████████████▍                                                                    | 31/201 [01:08<03:32,  1.25s/it]C:\Users\Alex\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pybaseball\datahelpers\postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 16%|████████████▉                                                                    | 32/201 [01:09<03:28,  1.23s/it]C:\Users\Alex\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pybaseball\datahelpers\postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
C:\Users\Alex\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pybaseball\datahelpers\postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 16%|█████████████▎                                                                   | 33/201 [01:10<03:10,  1.13s/it]C:\Users\Alex\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pybaseball\datahelpers\postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
 17%|█████████████▋                                                                   | 34/201 [01:11<02:51,  1.03s/it]C:\Users\Alex\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pybaseball\datahelpers\postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)
C:\Users\Alex\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pybaseball\datahelpers\postprocessing.py:59: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data_copy[column] = data_copy[column].apply(pd.to_datetime, errors='ignore', format=date_format)

(758890, 118)

In [28]:
statcast_data.head()

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,batter,pitcher,events,description,...,batter_days_until_next_game,api_break_z_with_gravity,api_break_x_arm,api_break_x_batter_in,arm_angle,attack_angle,attack_direction,swing_path_tilt,intercept_ball_minus_batter_pos_x_inches,intercept_ball_minus_batter_pos_y_inches
344,FF,2025-10-01,96.7,-2.27,5.8,"Smith, Cade",693307,671922,field_out,hit_into_play,...,1,1.04,1.03,1.03,40.4,-0.158216,30.463581,33.767846,36.037304,17.796143
354,FF,2025-10-01,96.3,-2.5,5.7,"Smith, Cade",693307,671922,NaN,swinging_strike,...,1,1.43,0.81,0.81,38.3,-7.785537,33.800045,37.751147,31.781746,12.476826
371,FF,2025-10-01,96.8,-2.51,5.65,"Smith, Cade",693307,671922,NaN,foul,...,1,1.32,0.56,0.56,36.6,7.256222,2.432506,43.471206,32.422763,27.80322
376,FF,2025-10-01,97.5,-2.42,5.72,"Smith, Cade",693307,671922,NaN,ball,...,1,1.25,0.73,0.73,37.3,<NA>,<NA>,<NA>,<NA>,<NA>
399,FF,2025-10-01,96.6,-2.47,5.66,"Smith, Cade",672761,671922,fielders_choice,hit_into_play,...,1,1.42,0.52,-0.52,36.1,-0.840287,7.724722,26.84735,27.45417,17.257405

In [29]:
statcast_data.columns

Index(['pitch_type', 'game_date', 'release_speed', 'release_pos_x',
       'release_pos_z', 'player_name', 'batter', 'pitcher', 'events',
       'description',
       ...
       'batter_days_until_next_game', 'api_break_z_with_gravity',
       'api_break_x_arm', 'api_break_x_batter_in', 'arm_angle', 'attack_angle',
       'attack_direction', 'swing_path_tilt',
       'intercept_ball_minus_batter_pos_x_inches',
       'intercept_ball_minus_batter_pos_y_inches'],
      dtype='object', length=118)

In [30]:
statcast_data.shape

(758890, 118)

In [31]:
tigers_pitches = statcast_data[
    (statcast_data['home_team'] == 'DET')|
    (statcast_data['away_team'] == 'DET')
]

tigers_pitches.shape

(51101, 118)

In [34]:
non_out_events = [
    'single',
    'double',
    'triple',
    'home_run',
    'walk',
    'hit_by_pitch',
    'intent_walk',
    'error',
    'field_error'
]

tigers_pitches['is_out'] = (
    tigers_pitches['events'].notna() &
    (~tigers_pitches['events'].isin(non_out_events))
)

tigers_pitches['outs'] = tigers_pitches['is_out'].astype(int)

C:\Users\Alex\AppData\Local\Temp\ipykernel_16432\1058370447.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tigers_pitches['is_out'] = (
C:\Users\Alex\AppData\Local\Temp\ipykernel_16432\1058370447.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tigers_pitches['outs'] = tigers_pitches['is_out'].astype(int)

In [36]:
pitching_game_level = (
    tigers_pitches
    .groupby(['game_pk', 'pitcher', 'player_name'], as_index=False)
    .agg({'outs': 'sum'})
)

pitching_game_level.head()

   game_pk  pitcher     player_name  outs
0   776151   571927    Matz, Steven     1
1   776151   592254   De León, José    17
2   776151   623149    Sewald, Paul     5
3   776151   663432  Rainey, Tanner     6
4   776151   663978  Paddack, Chris    13

In [37]:
pitching_game_level.shape

(1478, 4)

In [39]:
starter_per_game = (
    pitching_game_level
    .sort_values(['game_pk', 'outs'], ascending=[True, False])
)

starter_per_game.head()

   game_pk  pitcher     player_name  outs
1   776151   592254   De León, José    17
4   776151   663978  Paddack, Chris    13
3   776151   663432  Rainey, Tanner     6
2   776151   623149    Sewald, Paul     5
5   776151   669711  Weissert, Greg     3

In [40]:
starter_per_game.shape

(1478, 4)

In [41]:
starter_per_game = (
    tigers_pitches
    .groupby(['game_pk', 'pitcher', 'player_name'], as_index=False)
    .agg(
        outs=('events', lambda x: sum(
            ~x.isin([
                'single','double','triple','home_run',
                'walk','hit_by_pitch','intent_walk','error','field_error'
            ]) & x.notna()
        )),
        first_inning=('inning', 'min')
    )
)

In [42]:
starter_per_game = (
    starter_per_game
    .sort_values(['game_pk', 'first_inning', 'outs'], ascending=[True, True, False])
    .drop_duplicates(subset=['game_pk'], keep='first')
)

starter_per_game.shape

(175, 5)

In [43]:
starter_per_game[starter_per_game['outs'] >= 18]

      game_pk  pitcher      player_name  outs  first_inning
19     776181   663554      Mize, Casey    18             1
49     776218   668909  Williams, Gavin    18             1
88     776268   693821     Elder, Bryce    20             1
91     776275   669373    Skubal, Tarik    18             1
127    776332   800049      Mazur, Adam    18             1
...       ...      ...              ...   ...           ...
1267   778403   669373    Skubal, Tarik    18             1
1276   778433   527048    Pérez, Martín    18             1
1301   778469   622491   Castillo, Luis    21             1
1429   779118   669373    Skubal, Tarik    18             1
1473   813072   669373    Skubal, Tarik    22             1

[72 rows x 5 columns]

In [44]:
six_plus_starters = starter_per_game[starter_per_game['outs'] >= 18]

six_plus_starters.shape

(72, 5)

In [45]:
statcast_games = tigers_pitches[['game_pk', 'game_date']].drop_duplicates()

In [46]:
six_plus_starters = six_plus_starters.merge(
    statcast_games,
    on='game_pk',
    how='left'
)

In [47]:
six_plus_starters['game_date'] = pd.to_datetime(six_plus_starters['game_date'])

In [48]:
final_df = six_plus_starters.merge(
    tigers_schedule[['Date', 'W/L']],
    left_on='game_date',
    right_on='Date',
    how='left'
)

In [49]:
wins = final_df[final_df['W/L'] == 'W'].shape[0]
losses = final_df[final_df['W/L'] == 'L'].shape[0]

print("Record when starter went 6+ innings:")
print(f"{wins} - {losses}")

Record when starter went 6+ innings:
39 - 27

In [50]:
win_pct = wins / (wins + losses)

print(f"Win % when starter went 6+ innings: {win_pct:.3f}")

Win % when starter went 6+ innings: 0.591

In [51]:
summary = pd.DataFrame({
    "Condition": ["Starter ≥ 6 IP"],
    "Wins": [wins],
    "Losses": [losses],
    "Win_Percentage": [win_pct]
})

summary

        Condition  Wins  Losses  Win_Percentage
0  Starter ≥ 6 IP    39      27        0.590909